from django.shortcuts import render,redirect
from django.http import JsonResponse
from .forms import PatientRegistrationForm
from .models import PatientRegistration,PastMedHx
from django.core.paginator import Paginator
import json
from django.http import JsonResponse
from django.utils.timezone import localdate
from django.contrib.auth.decorators import login_required
# Create your views here.



##################################################################################################################################################################
# homepage
def homepage(request):
    todays_added = PatientRegistration.objects.filter(created_at__date=localdate())
    todays_pts_list = []
    for pt in todays_added:
        pmh_values = [(x.pmh) for x in pt.pmh.all()]
        data = {
            'operation':pt.operation,
            'age':pt.age,
            'complaint':pt.complaint,
            'labs': [(x.split(":")) for x in (pt.labs.split("\n"))],
            'rads': [(x.split(":")) for x in (pt.rads.split("\n"))],
        }
        todays_pts_list.append(data)
    return render(request,template_name='patients/homepage.html',context={'todays_added':todays_pts_list})


##################################################################################################################################################################
# adding_page

# instead of using @login_required you can use one of the following:>>

# from django.contrib.auth.mixins import LoginRequiredMixin
# class MyView(LoginRequiredMixin, View):
#     login_url = "/login/"
#     redirect_field_name = "redirect_to"


# if not request.user.is_authenticated:
#     return redirect(f"{settings.LOGIN_URL}?next={request.path}")

@login_required
def adding_page(request):
    if request.method == 'POST':
        form = PatientRegistrationForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.created_by = request.user
            patient.save()## save instance to create specific_id first before saving M2M column
            form.save_m2m() ## save ManyToMany column (pmh)
            return redirect("adding_page")
        # else :
            # return json.not_working_response
    else :
        form = PatientRegistrationForm()
    return render(request,"patients/adding_page.html",{'form':form})


##################################################################################################################################################################
#view_page
@login_required
def view_page(request):
    return render(request,"patients/view_page.html")


# ## generated by google
# def get_page_range(current_page,total_pages,show_pages=1):
#     start = max(1, current_page - (show_pages // 2))
#     stop = min(total_pages, start + show_pages -1)
#     if stop - start + 1 < show_pages :
#         start = max(1, stop-show_pages + 1)
#     return range(start , stop+1)


# @require_POST
@login_required
def view_check(request):
    page = int(request.GET.get('page',1))
    all_data = PatientRegistration.objects.all().order_by("-created_at")
    paginator = Paginator(all_data,4)
    page_cards = paginator.page(page)
    range = paginator.page_range
    if request.method == 'GET':
        return render(request,template_name="patients/view_check.html",context={'checked':True,'cards_data':page_cards,'range':range})
    if request.method == 'POST':
        id = (json.loads(request.body))['id']
        if id == 'btnradio1':
            check = True
        elif id == 'btnradio2':
            check = False
        return render(request,template_name="patients/view_check.html",context={'checked':check,'cards_data':page_cards,'range':range})

@login_required
def view_one(request):
    if request.method == 'POST':
        response = json.loads(request.body)#=>> {'name': {'name_to_search': 'fff'}}
        name_to_search = response['name']['name_to_search']
        patient = PatientRegistration.objects.filter(name=name_to_search).first()
        try: pmh = " & ".join([(x.pmh) for x in patient.pmh.all()])
        except : print('pt not found')
        data = {
            'operation':patient.operation,
            'name':patient.name,
            'age':patient.age,
            'gender':patient.gender,
            'complaint':patient.complaint,
            'pmh':pmh,
            'psh':patient.psh,
            'labs':patient.labs,
            'rads':patient.rads,
        }
                # products = list(Product.objects.values('id', 'name', 'price')) # Get as dict
        # return JsonResponse(products, safe=False)
        return JsonResponse(data)

switch_pgs = []
@login_required
def switch_pages(request):
    if request.method == 'POST':
        response = json.loads(request.body)
        name = response['name']
        switch_pgs.append(name)
        return JsonResponse({'status':'success'})
    
##################################################################################################################################################################
## editing page
@login_required
def editing_page(request):
    stored_name = switch_pgs[0] if switch_pgs else ''
    switch_pgs.clear()
    if request.method == 'POST':
        response = json.loads(request.body)
        name_to_update = response['name_to_update']
        patient = PatientRegistration.objects.filter(name=name_to_update).first()
        # pmh = [(x.pmh) for x in patient.pmh.all()]
        pmh_fields = ([(x.pmh) for x in (PastMedHx.objects.all())]) ## reached by trial error using dir()
        print(pmh_fields)
        pt_obj = {
            'operation':patient.operation,
            'name':patient.name,
            'age':patient.age,
            'gender':patient.gender,
            'complaint':patient.complaint,
            'pmh':pmh_fields,
            'psh':patient.psh,
            'labs':patient.labs,
            'rads':patient.rads,
        }
        return render(request,"patients/editing_form.html",context={'pt_data':pt_obj})
    return render(request,"patients/editing_page.html",context={'name':stored_name})

@login_required
def save_update(request):
    if request.method == 'POST':
        response = json.loads(request.body)
        patient = PatientRegistration.objects.filter(name=response['name_to_edit']).first()
        pmh_ids = []
        ## get pmh ids in PastMedHx table
        for x in response['pmh']:
            if x in [x.pmh for x in (PastMedHx.objects.all())]:
                # PastMedHx.objects.create(pmh=x)
                id = ((PastMedHx.objects.get(pmh=x).id))
                pmh_ids.append(id)
        ## replacing values in main table
        patient.pmh.set(pmh_ids)

        patient.name = response['name']
        patient.age = response['age']
        patient.gender = response['gender']
        patient.complaint = response['complaint']
        patient.psh = response['psh']
        patient.labs = response['labs']
        patient.rads = response['rads']
        patient.save()
        return JsonResponse('success',safe=False)
##################################################################################################################################################################

#deleting page
@login_required
def submit_delete(request):
    if request.method == 'POST':
        response = json.loads(request.body)
        name_to_delete = response['name'] # =>> name
        # print(name_to_delete)
        obj = PatientRegistration.objects.get(name=name_to_delete)
        obj.delete(user=request.user)
        return redirect('view_page/')
    

