# Generated by Django 6.0 on 2026-01-02 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMedHx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('Anticoagulant_stents', models.BooleanField(default=False)),
                ('NIDDM', models.BooleanField(default=False)),
                ('IDDM', models.BooleanField(default=False)),
                ('HTN', models.BooleanField(default=False)),
                ('IHD', models.BooleanField(default=False)),
                ('PU', models.BooleanField(default=False)),
                ('CKD', models.BooleanField(default=False)),
                ('Hepatic', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(max_length=10)),
                ('complaint', models.TextField()),
                ('psh', models.TextField()),
                ('labs', models.TextField()),
                ('rads', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_deleted', to=settings.AUTH_USER_MODEL)),
                ('pmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.pastmedhx')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
