# Generated by Django 6.0 on 2026-01-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('c', 'child')], max_length=1),
        ),
    ]
