# Generated by Django 6.0 on 2026-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientregistration_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastmedhx',
            name='Anticoagulant_stents',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='CKD',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='HTN',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='Hepatic',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='IDDM',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='IHD',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='NIDDM',
        ),
        migrations.RemoveField(
            model_name='pastmedhx',
            name='PU',
        ),
        migrations.AddField(
            model_name='pastmedhx',
            name='pmh',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
