# Generated by Django 6.0 on 2026-01-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_pastmedhx_anticoagulant_stents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='pmh',
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='pmh',
            field=models.ManyToManyField(to='patients.pastmedhx'),
        ),
    ]
