# Generated by Django 6.0 on 2026-01-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientregistration_pmh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='operation',
            field=models.CharField(choices=[('TURP', 'TURP'), ('TURP&Crushing', 'TURP&Crushing'), ('TVP', 'TVP'), ('Cystolithotripsy', 'Cystolithotripsy'), ('Cystolithotomy', 'Cystolithotomy'), ('Ureterolithotomy', 'Ureterolithotomy'), ('URS', 'URS'), ('DJ removal', 'DJ removal'), ('JJ fix', 'JJ fix'), ('D cysto(TURBT)', 'D cysto(TURBT)'), ('D cysto & proceed', 'D cysto & proceed'), ('Pyeloplasty', 'Pyeloplasty'), ('Nephrectomy(partial)', 'Nephrectomy(partial)'), ('Nephrectomy(total)', 'Nephrectomy(total)')], max_length=50),
        ),
    ]
