# Generated by Django 6.0 on 2026-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientregistration_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
